import { FieldValue } from 'firebase-admin/firestore'
import { HttpsError, onCall } from 'firebase-functions/v2/https'
import { z } from 'zod'
import { audit } from './audit.js'
import { db, id, managers, positiveQty, stockRoles } from './common.js'
import { requireAppCheck, requireAuth, requireRole, type Role } from './security.js'

export const moveStock = onCall({ enforceAppCheck: true }, async req=>{
  requireAppCheck(req); const {auth}=requireRole(req,stockRoles)
  const data=z.object({itemId:id,sourceLocationId:id,destinationLocationId:id,quantity:positiveQty,reason:z.string().min(3).max(300)}).parse(req.data)
  if(data.sourceLocationId===data.destinationLocationId)throw new HttpsError('invalid-argument','Origem e destino devem ser diferentes.')
  const srcRef=db.doc(`stockBalances/${data.sourceLocationId}_${data.itemId}`);const dstRef=db.doc(`stockBalances/${data.destinationLocationId}_${data.itemId}`);const movRef=db.collection('stockMovements').doc()
  await db.runTransaction(async tx=>{const src=await tx.get(srcRef);const current=Number(src.data()?.quantity||0);if(current<data.quantity)throw new HttpsError('failed-precondition','Saldo insuficiente.');const dst=await tx.get(dstRef);tx.set(srcRef,{itemId:data.itemId,locationId:data.sourceLocationId,quantity:current-data.quantity,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(dstRef,{itemId:data.itemId,locationId:data.destinationLocationId,quantity:Number(dst.data()?.quantity||0)+data.quantity,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(movRef,{...data,actorUid:auth.uid,createdAt:FieldValue.serverTimestamp()})})
  await audit({actorUid:auth.uid,actorEmail:auth.token.email as string|undefined,action:'STOCK_MOVE',resourceType:'stockMovement',resourceId:movRef.id,metadata:{itemId:data.itemId,sourceLocationId:data.sourceLocationId,destinationLocationId:data.destinationLocationId,quantity:data.quantity}})
  return {ok:true,id:movRef.id}
})

export const createMaterialRequest = onCall({enforceAppCheck:true},async req=>{
  requireAppCheck(req);const a=requireAuth(req);const role=a.token.role as Role|undefined;if(!role||(!managers.includes(role)&&role!=='LIDER_NUPDEC'))throw new HttpsError('permission-denied','Sem permissão.')
  const data=z.object({nupdecId:id,nupdecName:z.string().max(120).optional().default(''),itemId:id,itemName:z.string().max(160).optional().default(''),destinationLocationId:id,quantity:positiveQty,justification:z.string().min(3).max(1000)}).parse(req.data)
  if(role==='LIDER_NUPDEC'&&String(a.token.nupdecId||'')!==data.nupdecId)throw new HttpsError('permission-denied','Acesso limitado ao próprio NUPDEC.')
  const destination=await db.doc(`stockLocations/${data.destinationLocationId}`).get();if(!destination.exists||destination.data()?.type!=='NUPDEC'||String(destination.data()?.nupdecId||'')!==data.nupdecId)throw new HttpsError('invalid-argument','Destino não pertence ao NUPDEC informado.');const item=await db.doc(`inventoryItems/${data.itemId}`).get();if(!item.exists||item.data()?.active===false)throw new HttpsError('invalid-argument','Item inválido ou inativo.');
  const ref=db.collection('materialRequests').doc();await ref.set({...data,status:'PENDENTE',requestedByUid:a.uid,requestedByName:a.token.name||a.token.email||a.uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await audit({actorUid:a.uid,action:'MATERIAL_REQUEST_CREATE',resourceType:'materialRequest',resourceId:ref.id,metadata:{nupdecId:data.nupdecId,itemId:data.itemId,quantity:data.quantity}});return{ok:true,id:ref.id}
})

export const approveMaterialRequest = onCall({ enforceAppCheck:true }, async req=>{
  requireAppCheck(req);const {auth}=requireRole(req,stockRoles);const data=z.object({requestId:id,sourceLocationId:id}).parse(req.data);const ref=db.doc(`materialRequests/${data.requestId}`)
  await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new HttpsError('not-found','Solicitação não encontrada.');const r=snap.data()!;if(r.status!=='PENDENTE')throw new HttpsError('failed-precondition','Solicitação já processada.');const itemId=String(r.itemId);const qty=Number(r.quantity);const dest=String(r.destinationLocationId);const srcRef=db.doc(`stockBalances/${data.sourceLocationId}_${itemId}`);const dstRef=db.doc(`stockBalances/${dest}_${itemId}`);const src=await tx.get(srcRef);if(Number(src.data()?.quantity||0)<qty)throw new HttpsError('failed-precondition','Saldo insuficiente.');const dst=await tx.get(dstRef);tx.update(ref,{status:'APROVADA',approvedByUid:auth.uid,approvedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});tx.set(srcRef,{itemId,locationId:data.sourceLocationId,quantity:Number(src.data()?.quantity||0)-qty,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(dstRef,{itemId,locationId:dest,quantity:Number(dst.data()?.quantity||0)+qty,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(db.collection('stockMovements').doc(),{itemId,sourceLocationId:data.sourceLocationId,destinationLocationId:dest,quantity:qty,reason:`Solicitação ${data.requestId}`,actorUid:auth.uid,createdAt:FieldValue.serverTimestamp()})})
  await audit({actorUid:auth.uid,action:'MATERIAL_REQUEST_APPROVE',resourceType:'materialRequest',resourceId:data.requestId});return{ok:true}
})

export const rejectMaterialRequest = onCall({enforceAppCheck:true},async req=>{
  requireAppCheck(req);const{auth}=requireRole(req,stockRoles);const data=z.object({requestId:id,reason:z.string().min(3).max(500)}).parse(req.data);const ref=db.doc(`materialRequests/${data.requestId}`);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','Solicitação não encontrada.');if(s.data()?.status!=='PENDENTE')throw new HttpsError('failed-precondition','Solicitação já processada.');await ref.update({status:'REJEITADA',rejectionReason:data.reason,processedByUid:auth.uid,processedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await audit({actorUid:auth.uid,action:'MATERIAL_REQUEST_REJECT',resourceType:'materialRequest',resourceId:data.requestId});return{ok:true}
})

export const createCustody = onCall({enforceAppCheck:true},async req=>{requireAppCheck(req);const{auth}=requireRole(req,stockRoles);const data=z.object({itemId:id,sourceLocationId:id,quantity:positiveQty,holderUid:id,holderName:z.string().min(2).max(120),dueAt:z.string().max(40).optional(),condition:z.string().max(200).optional(),nupdecId:z.string().max(128).optional()}).parse(req.data);const custody=db.collection('custodies').doc();const src=db.doc(`stockBalances/${data.sourceLocationId}_${data.itemId}`);await db.runTransaction(async tx=>{const s=await tx.get(src);const q=Number(s.data()?.quantity||0);if(q<data.quantity)throw new HttpsError('failed-precondition','Saldo insuficiente.');tx.set(src,{itemId:data.itemId,locationId:data.sourceLocationId,quantity:q-data.quantity,updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(custody,{...data,status:'ATIVA',createdByUid:auth.uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()})});await audit({actorUid:auth.uid,action:'CUSTODY_CREATE',resourceType:'custody',resourceId:custody.id,metadata:{itemId:data.itemId,quantity:data.quantity}});return{ok:true,id:custody.id}})

export const returnCustody = onCall({enforceAppCheck:true},async req=>{requireAppCheck(req);const{auth}=requireRole(req,stockRoles);const data=z.object({custodyId:id,returnCondition:z.string().max(200).optional()}).parse(req.data);const ref=db.doc(`custodies/${data.custodyId}`);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Cautela não encontrada.');const c=s.data()!;if(c.status!=='ATIVA')throw new HttpsError('failed-precondition','Cautela já encerrada.');const bal=db.doc(`stockBalances/${c.sourceLocationId}_${c.itemId}`);const b=await tx.get(bal);tx.set(bal,{itemId:c.itemId,locationId:c.sourceLocationId,quantity:Number(b.data()?.quantity||0)+Number(c.quantity),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.update(ref,{status:'DEVOLVIDA',returnedAt:FieldValue.serverTimestamp(),returnedByUid:auth.uid,returnCondition:data.returnCondition||'',updatedAt:FieldValue.serverTimestamp()})});await audit({actorUid:auth.uid,action:'CUSTODY_RETURN',resourceType:'custody',resourceId:data.custodyId});return{ok:true}})
