import { FieldValue } from 'firebase-admin/firestore'
import { HttpsError, onCall } from 'firebase-functions/v2/https'
import { z } from 'zod'
import { audit } from './audit.js'
import { adminAuth, db, id } from './common.js'
import { requireAppCheck, requireRole } from './security.js'

const roleSchema=z.enum(['SUPER_ADMIN','GESTOR_COMPDEC','COORDENADOR','ALMOXARIFADO','LIDER_NUPDEC','CONSULTA'])
export const adminCreateUser = onCall({enforceAppCheck:true},async req=>{requireAppCheck(req);const{auth,role}=requireRole(req,['SUPER_ADMIN','GESTOR_COMPDEC']);const data=z.object({email:z.string().email(),displayName:z.string().min(2).max(120),role:roleSchema,nupdecId:z.string().max(128).optional()}).parse(req.data);if(role!=='SUPER_ADMIN'&&data.role==='SUPER_ADMIN')throw new HttpsError('permission-denied','Somente SUPER_ADMIN cria outro SUPER_ADMIN.');if(data.role==='LIDER_NUPDEC'&&!data.nupdecId)throw new HttpsError('invalid-argument','Líder deve ter NUPDEC vinculada.');const user=await adminAuth.createUser({email:data.email,displayName:data.displayName,emailVerified:false,disabled:false});await adminAuth.setCustomUserClaims(user.uid,{role:data.role,nupdecId:data.nupdecId||null});await db.doc(`users/${user.uid}`).set({uid:user.uid,email:data.email,displayName:data.displayName,role:data.role,nupdecId:data.nupdecId||null,active:true,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});const link=await adminAuth.generatePasswordResetLink(data.email);await audit({actorUid:auth.uid,action:'USER_CREATE',resourceType:'user',resourceId:user.uid,metadata:{role:data.role,nupdecId:data.nupdecId}});return{ok:true,uid:user.uid,passwordSetupLink:link}})

export const setUserRole = onCall({enforceAppCheck:true},async req=>{requireAppCheck(req);const{auth,role}=requireRole(req,['SUPER_ADMIN','GESTOR_COMPDEC']);const data=z.object({uid:id,role:roleSchema,nupdecId:z.string().max(128).optional()}).parse(req.data);if(role!=='SUPER_ADMIN'&&data.role==='SUPER_ADMIN')throw new HttpsError('permission-denied','Somente SUPER_ADMIN promove para SUPER_ADMIN.');if(data.role==='LIDER_NUPDEC'&&!data.nupdecId)throw new HttpsError('invalid-argument','Líder deve ter NUPDEC vinculada.');await adminAuth.setCustomUserClaims(data.uid,{role:data.role,nupdecId:data.nupdecId||null});await db.doc(`users/${data.uid}`).set({role:data.role,nupdecId:data.nupdecId||null,updatedAt:FieldValue.serverTimestamp()},{merge:true});await audit({actorUid:auth.uid,action:'USER_ROLE_CHANGE',resourceType:'user',resourceId:data.uid,metadata:{role:data.role,nupdecId:data.nupdecId}});return{ok:true}})
